- Name: 03_dataframe_introduction
- Author: Shamas Imran
- Desciption:  Basics of creating and exploring DataFrames in PySpark
- Date: 04-Oct-2025

In [1]:
from pyspark.sql import SparkSession
# Create a Spark session
spark = SparkSession.builder.appName("BigEntities").getOrCreate()

StatementMeta(, a1c6e66b-db88-4aec-bc6d-37db9b5fc616, 3, Finished, Available, Finished)

In [7]:
# Example array (list of tuples)
data = [
    (1, "Alice", 34),
    (2, "Bob", 45),
    (3, "Charlie", 29)
]

# Column names
columns = ["ID", "Name", "Age"]

# Create DataFrame from array
df = spark.createDataFrame(data, columns)

# Show DataFrame
display(df)

StatementMeta(, a1c6e66b-db88-4aec-bc6d-37db9b5fc616, 9, Finished, Available, Finished)

SynapseWidget(Synapse.DataFrame, 1ceb1e17-7bb7-418c-acab-7a3f96f35347)

In [ ]:
data = [("Alice", 34), ("Bob", 45), ("Charlie", 29)]
df = spark.createDataFrame(data)
#df.show()

display(df)

In [9]:
#df.printSchema()
schema = df.schema
display(schema)

StatementMeta(, a1c6e66b-db88-4aec-bc6d-37db9b5fc616, 11, Finished, Available, Finished)

StructType([StructField('ID', LongType(), True), StructField('Name', StringType(), True), StructField('Age', LongType(), True)])

In [20]:
from pyspark.sql.types import StructType, StructField, LongType, StringType

student_schema = StructType([StructField('ID', LongType(), False), StructField('Name', StringType(), True), StructField('Age', LongType(), True)])

student_data = [
        (1, "Alice", 34), 
        (2, "Bob", 45), 
        (3, "Charlie", 29),
        (4, "Shamas", 40),
        (5, "Nuzha", None)
        ]

df_student = spark.createDataFrame(student_data, student_schema)
df_student.show()

StatementMeta(, a1c6e66b-db88-4aec-bc6d-37db9b5fc616, 22, Finished, Available, Finished)

+---+-------+----+
| ID|   Name| Age|
+---+-------+----+
|  1|  Alice|  34|
|  2|    Bob|  45|
|  3|Charlie|  29|
|  4| Shamas|  40|
|  5|  Nuzha|NULL|
+---+-------+----+

In [26]:
from pyspark.sql.types import StructType, StructField, LongType, StringType

student_schema = StructType([StructField('ID', LongType(), False), StructField('Name', StringType(), True), StructField('Age', LongType(), True)])

student_data = [
        (1, "Alice", 34), 
        (2, "Bob", 45), 
        (3, "Charlie", 29),
        (4, "Shamas", 40),
        (5, "Nuzha", None),
        (None, "Nuzha", None),
        ]

df_student = spark.createDataFrame(student_data, student_schema,  None, False)
df_student.show()

StatementMeta(, a1c6e66b-db88-4aec-bc6d-37db9b5fc616, 28, Finished, Available, Finished)

+---+-------+----+
| ID|   Name| Age|
+---+-------+----+
|  1|  Alice|  34|
|  2|    Bob|  45|
|  3|Charlie|  29|
|  4| Shamas|  40|
|  5|  Nuzha|NULL|
|  0|  Nuzha|NULL|
+---+-------+----+

In [ ]:
help(spark.createDataFrame)

In [3]:
from pyspark.sql.types import *
# from pyspark.sql.types import StructType , StructField, LongType, StringType
import datetime as shamas

current_time = shamas.datetime.now()
print("Current date and time:", current_time)

# student_schema = StructType([StructField('ID', LongType(), False), StructField('Name', StringType(), True), StructField('Age', LongType(), True)])

# student_data = [
#         (1, "Alice", 34), 
#         (2, "Bob", 45), 
#         (3, "Charlie", 29),
#         (4, "Shamas", 40),
#         (5, "Nuzha", None)
#         ]

# df_student = spark.createDataFrame(student_data, student_schema)
# df_student.show()

StatementMeta(, 16d15f3d-b966-4070-aa85-9091464db4b4, 5, Finished, Available, Finished)

Current date and time: 2025-10-06 18:32:28.816470